@startuml
scale 1.2

(*) --> init
"init" --> menü kiírás
"menü kiírás" --> menü bevitel
if 1? then
    -->[yes] bevitel1
    if "ESC" then
        -->[yes] program vége
    else  

        if "0-9" then
        -->[yes] tarolas1
        -->szám kiírás1
            
            if "szám hossza 4?"
            -->[yes] bevitel vége
            --> (*)
            else 
            -->[no] bevitel
            endif
        
        else
        -->[yes] hiba kiírás
        --> bevitel
        endif

    endif
else 
    if 2? then
        -->[yes] bevitel2
        if "ESC" then
            -->[yes] program vége
        else  

            if "0-9" then
            -->[yes] tarolas
            -->szám kiírás
                
                if "szám hossza 4?"
                -->[yes] bevitel vége
                --> (*)
                else 
                -->[no] bevitel
                endif
            
            else
            -->[yes] hiba kiírás
            --> bevitel
            endif

        endif
    else
        if esc? then
            -->[yes] program vége
        else
            -->[no] menü bevitel
        endif
    endif
endif

 
 
"program vége" --> (*)

@enduml